# Generated by Django 5.0 on 2024-04-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='category2',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category3',
            name='category',
        ),
        migrations.CreateModel(
            name='StateData1',
            fields=[
                ('statedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.statedata')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
            ],
            bases=('polls.statedata',),
        ),
        migrations.CreateModel(
            name='StateData2',
            fields=[
                ('statedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.statedata')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('polls.statedata',),
        ),
        migrations.CreateModel(
            name='StateData3',
            fields=[
                ('statedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.statedata')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.BooleanField()),
            ],
            bases=('polls.statedata',),
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
    ]
