# Generated by Django 5.0 on 2024-04-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_statedata_remove_category2_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ICSE', 'ICSE'), ('CBSE', 'CBSE'), ('State Board', 'State Board')], max_length=100),
        ),
    ]
